import { Prodotto } from "./models/prodotto";
import { Cliente } from "./models/cliente";
import { ProcessoProduzione } from "./models/processoProduzione";
let costume1 = new Prodotto("costume da bagno", "intero", 123, "S", "nero", "disponibile");
let pareo1 = new Prodotto("pareo", "fantasia", 500, "XS", "rosso e bianco", "disponibile");
let cappello1 = new Prodotto("cappello", "panama", 404, "L", "bianco", "esaurito");
let cappello2 = new Prodotto("cappello", "berretto", 200, "L", "blu", "disponibile");
let cliente1 = new Cliente("Maria", "Rossi", "maria.rossi@hotmail.it", "postepay");
let cliente2 = new Cliente("Anna", "Garibaldi", "anna55@hotmail.it", "mastercard");
let cliente3 = new Cliente("Luca", "Verdi", "lucav@gmail.com", "bonifico");
let processo1 = new ProcessoProduzione("riciclo acqua", "implementare tecnologie per un minore utilizzo idrico e il recupero delle acque reflue", []);
let processo2 = new ProcessoProduzione("gestione degli scarti", "riduzione degli scarti di produzione, riciclo dei rifiuti tessili e adozione di pratiche di upcycling per trasformare i capi dismessi in nuovi prodotti. ", []);
cliente1.ordinaProdotto(costume1);
processo1.aggiungiProdotto(costume1);
cliente2.ordinaProdotto(pareo1);
processo1.aggiungiProdotto(pareo1);
cliente3.ordinaProdotto(cappello1);
processo2.aggiungiProdotto(cappello1);
cliente3.ordinaProdotto(cappello2);
processo2.aggiungiProdotto(cappello2);
//# sourceMappingURL=main.js.map